// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import DashboardDateController from "./dashboard_date_controller"
application.register("dashboard-date", DashboardDateController)

import DropdownMobileController from "./dropdown_mobile_controller"
application.register("dropdown-mobile", DropdownMobileController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PriceUpdateController from "./price_update_controller"
application.register("price-update", PriceUpdateController)

import ScrollIntoController from "./scroll_into_controller"
application.register("scroll-into", ScrollIntoController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
